import type { Metadata } from "next";
import { Poppins,Rubik } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer";

// Import and configure the Poppins font
const poppins = Poppins({
  weight: ['400', '600','100','200','500','700','800','900'],
  subsets: ['latin'],
  display: 'swap',
});
const rubik=Rubik(
  {
    weight: ['400', '600','500','700','800','900'],
    subsets: ['latin'],
    display: 'swap',
  }
)

export const metadata: Metadata = {
  title: "Biblio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: React.PropsWithChildren<{}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} ${rubik.className}`}>
       {children}
      
      <Footer/>
     
      </body>
    </html>
  );
}
